## References:
# https://git.io/Jf3l9
# https://circleci.com/docs/2.0/yarn/
# https://circleci.com/docs/2.0/caching/#yarn-node
# https://circleci.com/orbs/registry/orb/circleci/node
# https://discuss.circleci.com/t/circleci-2-1-config-overview/26057
version: 2.1

orbs:
  node: circleci/node@2.0.3
  slack: circleci/slack@4.2.0

jobs:
  prepare:
    executor:
      name: node/default
    steps:
      - checkout
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*Deploy has started :)*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
      - run:
          name: Meteor Install
          command: curl https://install.meteor.com/ | sh
      - run:
          name: MUP Install
          command: export NPM_CONFIG_PREFIX=~/.npm-global && sudo npm install -g mup && sudo chown -R $(whoami) ~/.npm
      - run:
          name: Install Dependencies
          command: meteor npm i
      - run:
          name: Deploy
          command: npm run deploy-staging
      - slack/notify:
          event: fail
          mentions: "@here"
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1

workflows:
  run-ci:
    jobs:
      - prepare
